spring:
  profiles:
    include:
      - app
      - secret

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope:
              - openid
              - profile
              - email

  datasource:
    driver-class-name: org.h2.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    # JPA ??? ???? ?? ??
    open-in-view: false
    # DataBase DDL ?? ??,??,?? ??
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # SQL ??
        show_sql: true
        # ?? SQL ??? ??? ??
        format_sql: true
        # ?? SQL ?? ??
        highlight_sql: true
        default_batch_fetch_size: 100
        query:
          fail_on_pagination_over_collection_fetch: true
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 50

logging:
  config: classpath:log4j2/log4j2-local.xml